### PR TITLE
HoP's Photobook steal objective

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

Add a steal objective for HoP since at this point they are objectiveless.

## Media

ss (2023-10-09 at 08 58 42)

## Breaking changes

**Changelog**

### CODE REVIEW

**Review by Colin-Tel — DISMISSED** [review]
Added comment where upstream file was touched. Looks good!

**Comment by Colin-Tel** [comment]
lol my dumb ass not noticing this is a draft

**Comment by ps3moira** [comment]
I love this, maybe add a few more pictures for the sprite that's poking out of the folder?

**Review by Colin-Tel — APPROVED** [review]
🐕

**Pull request merged**
