### PR TITLE
cap mass media articles

### PR DESCRIPTION
**Pull request by BasedUser**
no more 500px wide images, no more network lag

## About the PR
This PR caps the maximum news article size to 32KB, dampening network lag severely.
Client lag is also nonexistent now - previously occured at about 500KB on my relatively low end graphics card (Radeon HD 6850).
Mirrors [Delta-v#202](https://github.com/DeltaV-Station/Delta-v/pull/202).

**Media**
image
after applying a clientside cap
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no cl no fun

### CODE REVIEW

**Comment by DebugOk** [comment]
This doesnt work in its current state, and it might be better to upstream it

**Comment by BasedUser** [comment]
ok i'm blind give me some time to begin the killing

**Comment by deltanedas** [comment]
should just limit text to like 2kb and have a dedicated thing for adding images since clearly its a nice thing without needing a java script
also upstream killer

**Comment by DebugOk** [comment]
Stale, and probably should be upstreamed. Reopen if/when fixes get made

**Pull request closed without merging**
