### PR TITLE
Pebble Rebased

### PR DESCRIPTION
**Pull request by Carolyn3114**
## About the PR
Rebases pebble, with all the goodies ( I Think)

## Why / Balance
Lowpop map

## Technical details
peble

## Media
Pebble-0

PRs which make ingame changes (adding clothing, items, new features, etc) are required to have media attached that showcase the changes.
Small fixes/refactors are exempt.
Any media may be used in SS14 progres
s reports, with clear credit given.

If you're unsure whether your PR will require media, ask a maintainer.

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Colin-Tel** [comment]
My cursory observations/requests:

```
remove firelocks on top of maint hatches
make EVA room not HoP locked (opt for command or something)
HoL fax machine labelled "Quartermaster"
Mantis has detective door
Mantis gets his own fire alarm to lock himself in his room lol
Get rid of autolathe in Epi
Give Epi reverse-engineering machine
Atmos should be set up at least with a basic O2/N2 mixer. It is a small-pop map after all
```

**Comment by Carolyn3114** [comment]
> My cursory observations/requests:
> 
> ```
> remove firelocks on top of maint hatches
> make EVA room not HoP locked (opt for command or something)
> HoL fax machine labelled "Quartermaster"
> Mantis has detective door
> Mantis gets his own fire alarm to lock himself in his room lol
> Get rid of autolathe in Epi
> Give Epi reverse-engineering machine
> Atmos should be set up at least with a basic O2/N2 mixer. It is a small-pop map after all
> ```

why remove the autolathe in science?

**Comment by Carolyn3114** [comment]
thar

**Comment by toasterpm87** [comment]
> 
> 
> > My cursory observations/requests:
> > 
> > ```
> > remove firelocks on top of maint hatches
> > make EVA room not HoP locked (opt for command or something)
> > HoL fax machine labelled "Quartermaster"
> > Mantis has detective door
> > Mantis gets his own fire alarm to lock himself in his room lol
> > Get rid of autolathe in Epi
> > Give Epi reverse-engineering machine
> > Atmos should be set up at least with a basic O2/N2 mixer. It is a small-pop map after all
> > ```
> 
> why remove the autolathe in science?
> 

Because they want people to rely on other departments

**Comment by toasterpm87** [comment]
Just leave a tool box for them

**Comment by toasterpm87** [comment]
Also give them their mass media thing

**Comment by Carolyn3114** [comment]
where's the reporter's room?

**Comment by toasterpm87** [comment]
> where's the reporter's room?
> 

Fun fact, there isn't

**Comment by Carolyn3114** [comment]
> > where's the reporter's room?
> 
> Fun fact, there isn't

then they won't get a mass media console

**Comment by Carolyn3114** [comment]
I think this is in a pretty good condition now

**Comment by IamVelcroboy** [comment]
tests failing because missing text here 
image

**Comment by IamVelcroboy** [comment]
- Remove the DAWS
- Reason for 2 salvage magnets/mass scanners?
- Mapper;s choice but you can use the lockers with harduits in them instead of lockers _and_ hardsuit storage. For a small map like this might be nice. But your call.  

There's a couple places with double walls. Maybe always been there but, could/should be removed.
image
image

 
I would say it otherwise looks good.

**Comment by Carolyn3114** [comment]
> * Remove the DAWS
> * Reason for 2 salvage magnets/mass scanners?
> * Mapper;s choice but you can use the lockers with harduits in them instead of lockers _and_ hardsuit storage. For a small map like this might be nice. But your call.
> 
> There's a couple places with double walls. Maybe always been there but, could/should be removed. image image
> 
> I would say it otherwise looks good.

didn't catch the magnets and mass scanners, I'm pretty sure the double walls have been there, but I can remove them/replace them

**Comment by IamVelcroboy** [comment]
>I'm pretty sure the double walls have been there, but I can remove them/replace them

It's not the end of the world. 
More a preference of avoiding that where we can. I did notice some in Epi too but used clearly for decoration/shaping the room. So, that's fine.

**Comment by Carolyn3114** [comment]
where is the DAWS?

**Comment by IamVelcroboy** [comment]
Circuit board in maints above cargo.

**Comment by Carolyn3114** [comment]
fixed

**Comment by Colin-Tel** [comment]
@IamVelcroboy Let me know when this is ready to merge.

**Comment by IamVelcroboy** [comment]
1 more thing I just noticed is this glass over the rock right here 
image


Otherwise, It's good.

**Comment by Carolyn3114** [comment]
> 1 more thing I just noticed is this glass over the rock right here image
> 
> Otherwise, It's good.

it's been like that, didn't touch it

**Comment by IamVelcroboy** [comment]
I kinda figured. I just noticed it though. Seems odd. 🤷

**Comment by toasterpm87** [comment]
Once this gets merged i might start working on rock station

**Comment by Colin-Tel** [comment]
Did this get ninja bombing objectives / nav beacons added?

**Comment by Carolyn3114** [comment]
done

**Comment by Colin-Tel** [comment]
I'll merge this after I take a look at it in-game real quick.

**Comment by Colin-Tel** [comment]
image
Looks like the map won't load.

**Comment by Carolyn3114** [comment]
> image Looks like the map won't load.

the PR has the pebble file in it, and the prototype seem to work fine, I wonder what's happening?

**Comment by Colin-Tel** [comment]
> the PR has the pebble file in it, and the prototype seem to work fine, I wonder what's happening?

The error I sent references a line and column where the problem is.

image
lol I think I found it

**Comment by Carolyn3114** [comment]
> > the PR has the pebble file in it, and the prototype seem to work fine, I wonder what's happening?
> 
> The error I sent references a line and column where the problem is.
> 
> image lol I think I found it

damn it

**Comment by Carolyn3114** [comment]
Screenshot 2023-10-11 203258
I can't find it

**Comment by Carolyn3114** [comment]
image I can't find it

**Comment by Colin-Tel** [comment]
wtf lol nevermind I didn't pull the newest one

**Comment by Colin-Tel** [comment]
image
There's no tiny fans on the cargo dock.

**Comment by Colin-Tel** [comment]
image
this button isn't linked to the 4th door (like it matters that much)

**Comment by Carolyn3114** [comment]
got em

**Comment by Colin-Tel** [comment]
Adjusted the min population of Edge in this PR because it was 0. It is now 15.

**Review by Colin-Tel — APPROVED** [review]
Velcro said it's okay plus I checked it, so we mergin

**Pull request merged**
