### PR TITLE
Antag times

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

I expected someone to have done it by now.
~~Loneops uses the nukeops antag role so couldn't make them separate I guess.~~

## Why / Balance

Traitor: 24h
Nukie, regular: 30h and 10h security
Nukie, medic: 30h and 10h medical
Nukie, cmdr: 60h and 10h security and 10h command
Nukie, lone: 48h and 10h security
Revolutionary, head: 48h and 10h command
Infected, initial: 12h
Ninja: 72h

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
> > Loneops uses the nukeops antag role so couldn't make them separate I guess.
> 
> Whats stopping you from just adding it here https://github.com/DeltaV-Station/Delta-v-rebase/blob/master/Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml#L78

The YAML linter

**Comment by DebugOk** [comment]
> > > Loneops uses the nukeops antag role so couldn't make them separate I guess.
> > 
> > 
> > Whats stopping you from just adding it here https://github.com/DeltaV-Station/Delta-v-rebase/blob/master/Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml#L78
> 
> The YAML linter

You have to put it within GhostRole, not the entity

**Comment by FluffiestFloof** [comment]
> > > > Loneops uses the nukeops antag role so couldn't make them separate I guess.
> > > 
> > > 
> > > Whats stopping you from just adding it here https://github.com/DeltaV-Station/Delta-v-rebase/blob/master/Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml#L78
> > 
> > 
> > The YAML linter
> 
> You have to put it within GhostRole, not the entity

yep

**Review by Colin-Tel — APPROVED** [review]

**Comment by Colin-Tel** [comment]
My dumbass reviewing a merged branch

**Comment by FluffiestFloof** [comment]
blunt

**Pull request merged**
