### PR TITLE
Sync master up to 1/10

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
Gonna try making a habbit out of doing this every Sunday

### CODE REVIEW

**Comment by Colin-Tel** [comment]
image
Hell yeah

**Comment by deltanedas** [comment]
rouny

**Comment by DebugOk** [comment]
> build (windows-latest)

Cant anyways because a mystery test not running :clueless:

**Comment by DebugOk** [comment]
Oh I see, they removed the windows test

**Comment by deltanedas** [comment]
yes it was slow and usually failed

**Comment by Colin-Tel** [comment]
YOLO

**Pull request merged**
