### PR TITLE
Migration + Various items to fix missing prototypes in maps

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

We're missing book about alerts, shuttle and procedures.
Adds tinfoil hat back in Epi(Sci)Drobe.

Adds back the salvage gaming lore spawner.
Bluespace Powercell is only present in two maps with no research or recipe linked to it so it was replaced by a PowercellHigh.
If we really want it, we can always just make it a research thing.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by DebugOk** [comment]
@Colin-Tel or @IamVelcroboy review required for migrations because I'm not a mapping nerd 🤓

**Comment by IamVelcroboy** [comment]
looks like 
> LockerEpistemicsFilled: LockerScienceFilled

was already covered in another PR

**Comment by IamVelcroboy** [comment]
Also, mystagogue

**Comment by FluffiestFloof** [comment]
> looks like
> 
> > LockerEpistemicsFilled: LockerScienceFilled
> 
> was already covered in another PR

uh which one?

**Comment by IamVelcroboy** [comment]
hmm, not sure what's going on on my end...I think I maybe doubled something up...

**Review by Colin-Tel — APPROVED** [review]
Looks good to me, chief.

**Pull request merged**
