### PR TITLE
Some nyano spawners

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

Velcro said it would need to be re-added but cleaned up a bit.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
> Velcro said it would need to be re-added but cleaned up a bit.

They might be fine. Just now is a good time to clean them up if they need to be. but otherwise, should be good.

**Comment by Colin-Tel** [comment]
YAML Linter failing, seems to cite missing mob prototypes.

**Comment by FluffiestFloof** [comment]
Right so the missing ones are NPC version of Xenos, aka non ghostroles versions. Do we want to re-add those or directly use the normal xenos similar to the ones used in the vent event?

**Comment by IamVelcroboy** [comment]
We need the altered ones for Arena. I'll take a look in a min.

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
