### PR TITLE
Role time requirements

### PR DESCRIPTION
**Pull request by FluffiestFloof**
workin on it

## About the PR
**Currently requiring a decision for time:**
- [x] Keeping the Cadet / Interns as time limited or making them infinitely chosable?
- [x] Chemist time requirements?
- [x] Detective time requirements?
- [x] Paramedic time requirements?
- [x] Atmos Tech time requirements? Currently only requiring 4 hours as an intern/engineering seems low if antag allowed.
- [x] Should some civilian role require overall playtime? WD seems to have done so for Bartender, Chef, Mime and Lawyer.

**Currently requiring a decision for antag:**
- [x] CMO can no longer be a traitor. Keep or not.
- [x] Atmos Tech can currently be a traitor. Keep or not.

Roles access left untouched, need to figure out what we want out of them later.

~~Science and Epistemics needs to be combined~~

## Technical details
Kept all the roles access untouched. Will require to be decided upon.
Made the executive decision to give CMO 3 hours as Chemist because some of them really need to learn chemistry...
Gave the HoL 2 hours as a Courrier requirement.

Will need to reimplement the whitelist only role system at one point

## Breaking changes

**Changelog**

:cl:
- tweak: Give back all the jobs their proper time requirements.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
Will need some decision making on certain things marked in the PR's description

**Comment by Colin-Tel** [comment]
From top to bottom, my opinion:

Cadet/Interns should always be available, maps I think should allow for a larger capacity of these roles
Chemist should require 6 hours (~3 rounds) of medical gametime.
Detective should require 10 hours (~5 rounds) of security gametime. It should also be noted that the plan to have whitelist requirements would likely apply to joining as this role.
Paramedic should require 4 hours (~2 rounds) of medical gametime.
Atmospherics Technician should require 8 hours (~4 rounds) of engineering gametime.

As for civilian roles:
Bartender can have the 30 minute gametime requirement.
Chef can have the 30 minute gametime requirement. ("Noooo I wanna be able to join as a cannibal chef!!")
Mime can have a 2 hour (~1 round) gametime requirement.
Lawyer can have a 10 hour (~5 rounds) general gametime and 4 hour (~2 rounds) security gametime requirement.
Clown can have a 1 minute (~1/120th of a round) gametime requirement. 😁 

CMO should be antag-elligible.
HoL should be antag-elligible.
Atmos Tech should be antag-elligible.

**Comment by FluffiestFloof** [comment]
Done.
The clown is now time locked 🦊

**Review by Colin-Tel — DISMISSED** [review]

**Comment by rosieposieeee** [comment]
> The clown is now time locked 🦊

so real for this

**Comment by Colin-Tel** [comment]
image

**Pull request merged**
