### PR TITLE
Mr. Gog's GigaDrip Updatee

### PR DESCRIPTION
**Pull request by leonardo-dabepis**
## About the PR

better hat for mystagogue, plus now there are some inhand sprites that were missing. Also the mystagogue cloak is put in the locker properly.

## Why / Balance

I originally made these when I had less of an idea what I was doing and now I have more of an idea what I'm doing, also the new hat sprite is just better.

## Technical details

nah

## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

:elp:

**Changelog**

:cl:
- add: added some missing inhand sprites for the epi clothes
- tweak: mystagogue has a better hat now

### CODE REVIEW

**Review by DebugOk — APPROVED** [review]
Drip update

**Comment by IamVelcroboy** [comment]
This should have fixed [#222](https://github.com/DeltaV-Station/Delta-v-rebase/issues/222)

**Comment by FluffiestFloof** [comment]
> This should have fixed [#222](https://github.com/DeltaV-Station/Delta-v-rebase/issues/222)

Kinda don't because it's the PR that created the issue by renaming an item

**Comment by IamVelcroboy** [comment]
Sorry, meant [@223](https://github.com/DeltaV-Station/Delta-v-rebase/pull/223)

**Pull request merged**
