### PR TITLE
Amphora

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

Amphora.

## Media
ss (2023-10-05 at 05 23 33)

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by DebugOk** [comment]
Whats this supposed to be?

**Comment by IamVelcroboy** [comment]
It's basically "epi" decorations. But it holds reagents.

**Comment by FluffiestFloof** [comment]
Velcro just mentioned that it was "another little unique thing to add from Nyano"

**Comment by DebugOk** [comment]
Eh whatever. Dont see the reason for having it but idc

**Pull request merged**
