### PR TITLE
1984 the squished sprite specie

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

Disables dwarf from being a roundstart specie.

## Breaking changes

**Changelog**

:cl:
- remove: Removed Dwarf from roundstart choices.

### CODE REVIEW

**Review by DEATHB4DEFEAT — APPROVED** [review]
dumb species 🙂

**Comment by ps3moira** [comment]
can you make it a human trait?

**Comment by FluffiestFloof** [comment]
> can you make it a human trait?

Outside this PR's scope. :blunt:
Feel free to do that on another PR tho.

**Comment by DEATHB4DEFEAT** [comment]
> can you make it a human trait?

If you mean the size, I already have that coded, just need to make sure it works up here and I could PR it.

**Comment by ps3moira** [comment]
> > can you make it a human trait?
> 
> If you mean the size, I already have that coded, just need to make sure it works up here and I could PR it.

WOW that works perfectly then. Thanks! :D

**Comment by toasterpm87** [comment]
> > can you make it a human trait?
> 
> If you mean the size, I already have that coded, just need to make sure it works up here and I could PR it.

Can you use the felinid size for them, the current drawf size makes them look very janky looking

**Comment by DEATHB4DEFEAT** [comment]
> > > can you make it a human trait?
> > 
> > If you mean the size, I already have that coded, just need to make sure it works up here and I could PR it.
> 
> Can you use the felinid size for them, the current drawf size makes them look very janky looking

Yeah, it already scales evenly, the only y scaling is bad looking

**Pull request merged**
