### PR TITLE
Fixed the Visibility of 'Go Back' on Telegnostic Projections

### PR DESCRIPTION
**Pull request by PHCodes**
## About the PR

Fixed the Visibility of 'Go Back' on Telegnostic Projections
## Why / Balance

Visibility of actions is now the owner's own visibility + 1. So the action to go back was set to vis mask 5, which was unviewable by anyone and was not defined. 
Couldn't see the 'go back' action. 
## Technical details

Added a new vis mask for Telegnostic Projections. 
## Media

https://cdn.discordapp.com/attachments/1150555473699934370/1165034322739351612/image.png?ex=654561c3&is=6532ecc3&hm=894dcbb137affa75cd2084ba2195e2d084d7ae3235e7e26d2f5c67dd9574855b&
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by DebugOk** [comment]
Does this mean they are still visible to people wearing, say, a tinfoil hat?

**Comment by PHCodes** [comment]
I didn't touch anything to do with people SEEING them. I only changed what they can SEE.

**Comment by DebugOk** [comment]
If they arent visible to people wearing tinfoil hats, I'll probably disable the power for the time. But for now I just want this merged so I have a working build

**Comment by PHCodes** [comment]
I'm just saying this PR is totally unrelated to that. We'll get feedback in the beta hopefully that'll tell us if that's working as intended or not.

**Pull request merged**
